### ISSUE TITLE
Handle Kotlin

### ISSUE THREAD

**Issue by johnsonr** [atomist/spring-automation#8]
Migrate the KotlinSpring5 generator from https://github.com/atomist-blogs/spring5-kotlin. Collapse class hierarchies where possible.

Update the blog posts as necessary.

-   https://the-composition.com/turn-any-repo-into-a-software-factory-exploring-spring-5-and-kotlin-2f58283421a2
-   https://the-composition.com/atomist-generator-deep-dive-c122561f6449

**Comment by ddgenome** [comment]
This is complete and/or moved to SDM.
